var data={
    value:[
    {
    room_id:1,
    type:"No/AC",
    location:2,
    charge:3242,
    available:"AVAILABLE",
    paymentDone:"PAID"
    },
    {
        room_id:1,
        type:"No/AC",
        location:2,
        charge:3242,
        available:"AVAILABLE",
        paymentDone:"PAID"
    },
    {
        room_id:1,
        type:"No/AC",
        location:2,
        charge:3242,
        available:"AVAILABLE",
        paymentDone:"PAID"
    }
  ]
}