var data={
    value:[
    {
    room_id:1,
    type:"No/AC",
    location:2,
    charge:3242,
    available:"AVAILABLE",
    paymentDone:"PAID"
    },
    {
        room_id:1,
        type:"No/AC",
        location:2,
        charge:3242,
        available:"AVAILABLE",
        paymentDone:"PAID"
    },
    {
        room_id:1,
        type:"No/AC",
        location:2,
        charge:3242,
        available:"AVAILABLE",
        paymentDone:"PAID"
    }
  ]
}

data=[{"room_id":0,"type":"AC","location":0,"charge":0,"available":"AVAILABLE","paymentDone":"DONE"},{"room_id":0,"type":"AC","location":0,"charge":0,"available":"AVAIL","paymentDone":"DONE"},{"room_id":0,"type":"AC","location":0,"charge":0,"available":"AVAIL","paymentDone":"DONE"},{"room_id":0,"type":"AC","location":0,"charge":0,"available":"AVAIL","paymentDone":"DONE"}]